name: "Cache Trust Scores"
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0,12 * * *" # Every 12 hours.

jobs:
  convo_crons:
    runs-on: ubuntu-latest
    name: Cache Trust Scores
    steps:
    - name: checkout
      uses: actions/checkout@v2.3.4
    - uses: actions/setup-node@v2
      with:
        node-version: 16
    - uses: bahmutov/npm-install@v1
    - uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Cache Trust Scores
      env:
        TEXTILE_THREADID: ${{ secrets.TEXTILE_THREADID }}
        TEXTILE_PK: ${{ secrets.TEXTILE_PK }}
        TEXTILE_HUB_KEY_DEV: ${{ secrets.TEXTILE_HUB_KEY_DEV }}
        NFTSTORAGE_KEY: ${{ secrets.NFTSTORAGE_KEY }}
      run: node ./cron/cacheTrustScore.js

