name: "Cache Uniswap Sybil Scores"
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *" # Every Day

jobs:
  convo_crons:
    runs-on: ubuntu-latest
    name: Cache Sybil Scores
    steps:
    - name: checkout
      uses: actions/checkout@v2.3.4
    - uses: actions/setup-node@v2
      with:
        node-version: 16
    - uses: actions/cache@v2
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - uses: bahmutov/npm-install@v1
    - name: Cache Sybil Scores
      env:
        TEXTILE_THREADID: ${{ secrets.TEXTILE_THREADID }}
        TEXTILE_PK: ${{ secrets.TEXTILE_PK }}
        TEXTILE_HUB_KEY_DEV: ${{ secrets.TEXTILE_HUB_KEY_DEV }}
      run: node ./cron/cacheSybil.js

