name: "Cache Trust Scores"
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0,6,12,18 * * *" # Every 6 hours.

jobs:
  convo_crons:
    runs-on: ubuntu-latest
    name: Cache Trust Scores
    steps:
    - name: checkout
      uses: actions/checkout@v2.3.4
    - uses: actions/setup-node@v2
      with:
        node-version: 16
    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
    - uses: actions/cache@v2
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - uses: bahmutov/npm-install@v1
    - name: Cache Trust Scores
      env:
        TEXTILE_THREADID: ${{ secrets.TEXTILE_THREADID }}
        TEXTILE_PK: ${{ secrets.TEXTILE_PK }}
        TEXTILE_HUB_KEY_DEV: ${{ secrets.TEXTILE_HUB_KEY_DEV }}
        NFTSTORAGE_KEY: ${{ secrets.NFTSTORAGE_KEY }}
      run: node ./cron/cacheTrustScore.js

